---
- hosts: ansible

  tasks:
  - name: create docker image
    command: docker build -t app:latest .
    args:
      chdir: /opt/docker
  - name: create tag to push image in dockerhub
    command: docker tag app:latest draganov07/app:latest

  - name: push image
    command: docker push draganov07/app:latest
